# Generated by Django 5.0.1 on 2024-01-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="path",
            field=models.FileField(upload_to="uploadApp/photo_and_video/"),
        ),
    ]
