# Generated by Django 5.0.1 on 2024-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadApp", "0002_alter_post_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="path",
        ),
        migrations.AddField(
            model_name="post",
            name="file_path",
            field=models.FileField(blank=True, upload_to="uploadApp/files/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
